import 'package:flutter/material.dart';

import '../../../l10n/app_localizations.dart';

import '../../../theme/premium_looks.dart';
import 'detail_theme.dart';

/// The twenty shipped looks.
///
/// Ported from `detail_themes_mockup/`, where all twenty are rendered on one
/// identical layout — the proof that a token layer is what was missing rather
/// than more layouts.
///
/// Note on weights: CSS allows 750 and 780; Flutter has nine `FontWeight`
/// values. The mock's 750/780 snap to w700/w800 here. That is deliberate, not
/// a transcription error.
abstract final class DetailThemes {
  // ── I · SIGNAL GOLD — today's look, exactly ─────────────────────────────
  //
  // Every value below is what the app renders right now. This is the
  // regression test for the whole refactor: if Signal moves, something is
  // wrong. See plan §3.2a.
  static const signal = DetailTheme(
    id: 'signal',
    label: 'Signal Gold',
    subtitle: "Today's look — dark glass, gold reserved for state",
    ground: Color(0xFF0B0B0E),
    pane: Color(0xFF0E0B14),
    railBg: Color(0xFF0A0A0D),
    panel: Color(0x12FFFFFF),
    hair: Color(0x1CFFFFFF),
    // Pure white at the shipped alphas — Signal is the CURRENT look, so its
    // text must match what shipped, not a warmer off-white that reads dimmer.
    tx: Color(0xFFFFFFFF),
    tx2: Color(0xA3FFFFFF), // the shipped 64%
    tx3: Color(0x66FFFFFF), // the shipped 40%
    accent: Color(0xFFABA124),
    state: Color(0xFFF5B942),
    callout: Color(0xFFF5B942),
    calloutText: Color(0xFF2A1E02),
    award: Color(0xFFF5B942),
    rating: Color(0xFFF5C518),
    focus: Color(0xFFFBBF24),
    useArtworkAccent: true,
    washOpacity: 0.16,
    // Shipped Signal has no monospace anywhere. The mono default belongs to
    // the themes whose mocks asked for it, not to today's look.
    dataFont: DetailFontRole.sans,
    // Signal's shipped geometry: 4px chips, 8px artwork, and the opaque
    // placeholder its image blocks have always used.
    radiusSm: 4,
    radiusImg: 8,
    imageBg: Color(0xFF1A1622),
    btnFill: Color(0xFFF6F5F0),
    btnText: Color(0xFF0D0D10),
    ghostFill: Color(0x12FFFFFF),
    ghostBorder: Color(0x1CFFFFFF),
    ghostText: Color(0xFFFFFFFF),
  );

  // ── II · NOIR ───────────────────────────────────────────────────────────
  static const noir = DetailTheme(
    id: 'noir',
    label: 'Noir',
    subtitle: 'Black and white with one red — square, uppercase, high contrast',
    ground: Color(0xFF0A0A0A),
    pane: Color(0xFF0A0A0A),
    railBg: Color(0xFF050505),
    panel: Color(0x0DFFFFFF),
    hair: Color(0x38FFFFFF),
    tx: Color(0xFFFFFFFF),
    tx2: Color(0xADFFFFFF),
    tx3: Color(0x6BFFFFFF),
    accent: Color(0xFFFFFFFF),
    state: Color(0xFFFF3B30),
    callout: Color(0xFFFF3B30),
    calloutText: Color(0xFFFFFFFF),
    award: Color(0xFFFFFFFF),
    rating: Color(0xFFFFFFFF),
    focus: Color(0xFFFFFFFF),
    radius: 0,
    radiusSm: 0,
    radiusBtn: 0,
    radiusImg: 0,
    radiusCast: 0,
    displayUpper: true,
    displayTracking: 0.4,
    displaySize: 21,
    slabTracking: 2.8,
    btnFill: Color(0xFFFFFFFF),
    btnText: Color(0xFF000000),
    ghostFill: Color(0x00000000),
    ghostBorder: Color(0x80FFFFFF),
    ghostText: Color(0xFFFFFFFF),
    focusWidth: 3,
  );

  // ── III · BROADSHEET (light) ────────────────────────────────────────────
  static const broadsheet = DetailTheme(
    id: 'broadsheet',
    label: 'Broadsheet',
    subtitle: 'Warm paper, black serif, hairline rules — a printed page',
    ground: Color(0xFFF3EFE7),
    pane: Color(0xFFEFEAE0),
    railBg: Color(0xFFE7E1D5),
    panel: Color(0x0F1C1812),
    hair: Color(0x2E1C1812),
    tx: Color(0xFF16130E),
    tx2: Color(0xB816130E),
    tx3: Color(0x7316130E),
    accent: Color(0xFF8A2B18),
    state: Color(0xFF8A2B18),
    callout: Color(0xFF8A2B18),
    calloutText: Color(0xFFF3EFE7),
    award: Color(0xFF8A2B18),
    rating: Color(0xFF16130E),
    focus: Color(0xFF8A2B18),
    lightGround: true,
    radius: 2,
    radiusSm: 2,
    radiusBtn: 2,
    radiusImg: 2,
    radiusCast: 2,
    displayFont: DetailFontRole.serif,
    bodyFont: DetailFontRole.serif,
    displayWeight: FontWeight.w600,
    displayTracking: -0.3,
    displaySize: 26,
    slabTracking: 2,
    slabWeight: FontWeight.w700,
    btnFill: Color(0xFF16130E),
    btnText: Color(0xFFF3EFE7),
    ghostFill: Color(0x00000000),
    ghostBorder: Color(0x591C1812),
    ghostText: Color(0xFF16130E),
    focusWidth: 2,
  );

  // ── IV · PHOSPHOR ───────────────────────────────────────────────────────
  static const phosphor = DetailTheme(
    id: 'phosphor',
    label: 'Phosphor',
    subtitle: 'Amber on true black, monospace throughout',
    ground: Color(0xFF000000),
    pane: Color(0xFF000000),
    railBg: Color(0xFF000000),
    panel: Color(0x0DFFB000),
    hair: Color(0x47FFB000),
    tx: Color(0xFFFFB000),
    tx2: Color(0xA8FFB000),
    tx3: Color(0x61FFB000),
    accent: Color(0xFFFFB000),
    state: Color(0xFF37E06A),
    callout: Color(0xFF37E06A),
    calloutText: Color(0xFF001A08),
    award: Color(0xFFFFB000),
    rating: Color(0xFFFFB000),
    focus: Color(0xFFFFB000),
    radius: 0,
    radiusSm: 0,
    radiusBtn: 0,
    radiusImg: 0,
    radiusCast: 0,
    displayFont: DetailFontRole.mono,
    bodyFont: DetailFontRole.mono,
    displayWeight: FontWeight.w700,
    displayUpper: true,
    displayTracking: 1.1,
    displaySize: 19,
    slabTracking: 2.4,
    btnFill: Color(0xFFFFB000),
    btnText: Color(0xFF000000),
    ghostFill: Color(0x00000000),
    ghostBorder: Color(0x73FFB000),
    ghostText: Color(0xFFFFB000),
    focusWidth: 2,
  );

  // ── V · AURORA ──────────────────────────────────────────────────────────
  static const aurora = DetailTheme(
    id: 'aurora',
    label: 'Aurora',
    subtitle: 'Frosted panels on deep indigo — soft, rounded, modern',
    ground: Color(0xFF0D1030),
    pane: Color(0xFF141845),
    railBg: Color(0xFF0F1236),
    panel: Color(0x17FFFFFF),
    hair: Color(0x29FFFFFF),
    tx: Color(0xFFF4F3FF),
    tx2: Color(0xB3F4F3FF),
    tx3: Color(0x73F4F3FF),
    accent: Color(0xFF8FB8FF),
    state: Color(0xFF7DE2C3),
    callout: Color(0xFF7DE2C3),
    calloutText: Color(0xFF04241B),
    award: Color(0xFF8FB8FF),
    rating: Color(0xFF8FB8FF),
    focus: Color(0xFFBFD4FF),
    radius: 18,
    radiusSm: 12,
    radiusImg: 14,
    displayWeight: FontWeight.w700,
    displayTracking: -0.5,
    btnFill: Color(0xFFF4F3FF),
    btnText: Color(0xFF161A3A),
    ghostFill: Color(0x1FFFFFFF),
    ghostBorder: Color(0x38FFFFFF),
    ghostText: Color(0xFFF4F3FF),
    shadow: [
      BoxShadow(
        color: Color(0xB3000000),
        blurRadius: 40,
        offset: Offset(0, 12),
      ),
    ],
  );

  // ── VI · CONCRETE (light) ───────────────────────────────────────────────
  static const concrete = DetailTheme(
    id: 'concrete',
    label: 'Concrete',
    subtitle: 'Flat grey, hard borders, offset blocks — brutalist',
    ground: Color(0xFFC9C7C1),
    pane: Color(0xFFDEDCD6),
    railBg: Color(0xFFC9C7C1),
    panel: Color(0xFFDEDCD6),
    hair: Color(0xFF141414),
    tx: Color(0xFF141414),
    tx2: Color(0xBD141414),
    tx3: Color(0x80141414),
    accent: Color(0xFF1A38E0),
    state: Color(0xFFE03A1A),
    callout: Color(0xFFE03A1A),
    calloutText: Color(0xFFF5F4F0),
    award: Color(0xFF141414),
    rating: Color(0xFF141414),
    focus: Color(0xFF1A38E0),
    lightGround: true,
    radius: 0,
    radiusSm: 0,
    radiusBtn: 0,
    radiusImg: 0,
    radiusCast: 0,
    displayWeight: FontWeight.w800,
    displayUpper: true,
    displayTracking: -0.4,
    displaySize: 24,
    slabTracking: 1,
    btnFill: Color(0xFF141414),
    btnText: Color(0xFFF5F4F0),
    ghostFill: Color(0x00000000),
    ghostBorder: Color(0xFF141414),
    ghostText: Color(0xFF141414),
    focusWidth: 3,
    shadow: [
      BoxShadow(color: Color(0xFF141414), offset: Offset(4, 4), blurRadius: 0),
    ],
  );

  // ── VII · VELVET ────────────────────────────────────────────────────────
  static const velvet = DetailTheme(
    id: 'velvet',
    label: 'Velvet',
    subtitle: 'Oxblood and gold leaf, light serif — quiet and expensive',
    ground: Color(0xFF180A10),
    pane: Color(0xFF1D0D14),
    railBg: Color(0xFF150910),
    panel: Color(0x12D6B26A),
    hair: Color(0x42D6B26A),
    tx: Color(0xFFF6EBDA),
    tx2: Color(0xADF6EBDA),
    tx3: Color(0x6BF6EBDA),
    accent: Color(0xFFD6B26A),
    state: Color(0xFFD6B26A),
    callout: Color(0xFFD6B26A),
    calloutText: Color(0xFF180A10),
    award: Color(0xFFD6B26A),
    rating: Color(0xFFD6B26A),
    focus: Color(0xFFE8CE96),
    radius: 3,
    radiusSm: 2,
    radiusBtn: 3,
    radiusImg: 3,
    displayFont: DetailFontRole.serif,
    displayWeight: FontWeight.w500,
    displayTracking: 0,
    displaySize: 27,
    slabTracking: 3,
    slabWeight: FontWeight.w600,
    btnFill: Color(0xFFD6B26A),
    btnText: Color(0xFF180A10),
    ghostFill: Color(0x00000000),
    ghostBorder: Color(0x73D6B26A),
    ghostText: Color(0xFFF6EBDA),
    focusWidth: 1.5,
    dividerGradient: LinearGradient(
      colors: [Color(0xFFD6B26A), Color(0x00D6B26A)],
    ),
  );

  // ── VIII · BLUEPRINT ────────────────────────────────────────────────────
  static const blueprint = DetailTheme(
    id: 'blueprint',
    label: 'Blueprint',
    subtitle: 'Deep teal, thin cyan lines, a visible grid — technical drawing',
    ground: Color(0xFF062028),
    pane: Color(0xFF07242D),
    railBg: Color(0xFF051C23),
    panel: Color(0x0D5EEAFF),
    hair: Color(0x4D5EEAFF),
    tx: Color(0xFFDFF7FD),
    tx2: Color(0xA8DFF7FD),
    tx3: Color(0x66DFF7FD),
    accent: Color(0xFF5EEAFF),
    state: Color(0xFF5EEAFF),
    callout: Color(0xFF5EEAFF),
    calloutText: Color(0xFF04222A),
    award: Color(0xFF5EEAFF),
    rating: Color(0xFF5EEAFF),
    focus: Color(0xFF5EEAFF),
    radius: 0,
    radiusSm: 0,
    radiusBtn: 0,
    radiusImg: 0,
    radiusCast: 0,
    displayFont: DetailFontRole.mono,
    displayWeight: FontWeight.w600,
    displayUpper: true,
    displayTracking: 1.8,
    displaySize: 18,
    slabTracking: 2.6,
    btnFill: Color(0x00000000),
    btnText: Color(0xFF5EEAFF),
    btnWeight: FontWeight.w600,
    btnBorder: Color(0xFF5EEAFF),
    ghostFill: Color(0x00000000),
    ghostBorder: Color(0x665EEAFF),
    ghostText: Color(0xFFDFF7FD),
    focusWidth: 1.5,
    grid: true,
  );

  // ── IX · BROADCAST ──────────────────────────────────────────────────────
  static const broadcast = DetailTheme(
    id: 'broadcast',
    label: 'Broadcast',
    subtitle: 'Navy and one bright yellow, chunky — unmissable at three metres',
    ground: Color(0xFF0E1A3C),
    pane: Color(0xFF132250),
    railBg: Color(0xFF0C1734),
    panel: Color(0x12FFFFFF),
    hair: Color(0x24FFFFFF),
    tx: Color(0xFFFFFFFF),
    tx2: Color(0xB8FFFFFF),
    tx3: Color(0x75FFFFFF),
    accent: Color(0xFFFFD400),
    state: Color(0xFFFFD400),
    callout: Color(0xFFFFD400),
    calloutText: Color(0xFF0E1A3C),
    award: Color(0xFFFFD400),
    rating: Color(0xFFFFD400),
    focus: Color(0xFFFFD400),
    radius: 8,
    radiusSm: 6,
    radiusBtn: 8,
    radiusImg: 8,
    radiusCast: 8,
    displayWeight: FontWeight.w800,
    displayTracking: -0.7,
    displaySize: 25,
    slabTracking: 1.2,
    btnFill: Color(0xFFFFD400),
    btnText: Color(0xFF0E1A3C),
    btnWeight: FontWeight.w800,
    ghostFill: Color(0x1FFFFFFF),
    ghostBorder: Color(0x00000000),
    ghostText: Color(0xFFFFFFFF),
    focusWidth: 4,
  );

  // ── X · SEPIA ───────────────────────────────────────────────────────────
  static const sepia = DetailTheme(
    id: 'sepia',
    label: 'Sepia',
    subtitle: 'Warm brown and cream with grain — nothing shouts',
    ground: Color(0xFF241C14),
    pane: Color(0xFF2B2118),
    railBg: Color(0xFF201810),
    panel: Color(0x0FE8D6BA),
    hair: Color(0x33E8D6BA),
    tx: Color(0xFFEFE3D0),
    tx2: Color(0xA8EFE3D0),
    tx3: Color(0x6BEFE3D0),
    accent: Color(0xFFC98A3E),
    state: Color(0xFF9BA86A),
    callout: Color(0xFFC98A3E),
    calloutText: Color(0xFF241C14),
    award: Color(0xFFC98A3E),
    rating: Color(0xFFC98A3E),
    focus: Color(0xFFE3B476),
    radius: 4,
    radiusSm: 3,
    radiusBtn: 4,
    radiusImg: 4,
    displayFont: DetailFontRole.serif,
    displayWeight: FontWeight.w600,
    displayTracking: -0.2,
    displaySize: 25,
    slabTracking: 2.2,
    btnFill: Color(0xFFEFE3D0),
    btnText: Color(0xFF241C14),
    ghostFill: Color(0x00000000),
    ghostBorder: Color(0x4DE8D6BA),
    ghostText: Color(0xFFEFE3D0),
    grain: 0.09,
  );

  // ── XI · OBSIDIAN ───────────────────────────────────────────────────────
  static const obsidian = DetailTheme(
    id: 'obsidian',
    label: 'Obsidian',
    subtitle: 'True black and one scarlet — artwork is the loudest thing',
    ground: Color(0xFF000000),
    pane: Color(0xFF050505),
    railBg: Color(0xFF000000),
    panel: Color(0x0FFFFFFF),
    hair: Color(0x1AFFFFFF),
    tx: Color(0xFFFFFFFF),
    tx2: Color(0xA8FFFFFF),
    tx3: Color(0x66FFFFFF),
    accent: Color(0xFFE50914),
    state: Color(0xFFE50914),
    callout: Color(0xFFE50914),
    calloutText: Color(0xFFFFFFFF),
    award: Color(0xFFE50914),
    rating: Color(0xFFFFFFFF),
    focus: Color(0xFFFFFFFF),
    radius: 4,
    radiusSm: 3,
    radiusBtn: 4,
    radiusImg: 3,
    radiusCast: 3,
    displayWeight: FontWeight.w800,
    displayTracking: -0.9,
    displaySize: 26,
    slabTracking: 1.4,
    btnFill: Color(0xFFFFFFFF),
    btnText: Color(0xFF000000),
    btnWeight: FontWeight.w800,
    ghostFill: Color(0x24FFFFFF),
    ghostBorder: Color(0x00000000),
    ghostText: Color(0xFFFFFFFF),
    focusWidth: 3,
  );

  // ── XII · HALO ──────────────────────────────────────────────────────────
  static const halo = DetailTheme(
    id: 'halo',
    label: 'Halo',
    subtitle: 'Charcoal and an ultra-light display — restraint as luxury',
    ground: Color(0xFF141518),
    pane: Color(0xFF17181C),
    railBg: Color(0xFF121316),
    panel: Color(0x0DFFFFFF),
    hair: Color(0x17FFFFFF),
    tx: Color(0xFFF5F6F8),
    tx2: Color(0x9EF5F6F8),
    tx3: Color(0x5CF5F6F8),
    accent: Color(0xFFC9D2DE),
    state: Color(0xFF8FA6C4),
    callout: Color(0xFF8FA6C4),
    calloutText: Color(0xFF0B1220),
    award: Color(0xFFC9D2DE),
    rating: Color(0xFFC9D2DE),
    focus: Color(0xFFFFFFFF),
    radius: 14,
    radiusSm: 10,
    radiusImg: 10,
    displayWeight: FontWeight.w300,
    displayTracking: -0.6,
    displaySize: 29,
    slabTracking: 2,
    slabWeight: FontWeight.w600,
    btnFill: Color(0xFFF5F6F8),
    btnText: Color(0xFF141518),
    btnWeight: FontWeight.w600,
    ghostFill: Color(0x14FFFFFF),
    ghostBorder: Color(0x24FFFFFF),
    ghostText: Color(0xFFF5F6F8),
    focusWidth: 2,
  );

  // ── XIII · PRESTIGE ─────────────────────────────────────────────────────
  static const prestige = DetailTheme(
    id: 'prestige',
    label: 'Prestige',
    subtitle: 'Purple-black with a violet gradient — depth without artwork',
    ground: Color(0xFF100418),
    pane: Color(0xFF150620),
    railBg: Color(0xFF0C0312),
    panel: Color(0x1AA855F7),
    hair: Color(0x33C496FF),
    tx: Color(0xFFF4EDFF),
    tx2: Color(0xA8F4EDFF),
    tx3: Color(0x66F4EDFF),
    accent: Color(0xFFB07BFF),
    state: Color(0xFFC77DFF),
    callout: Color(0xFFC77DFF),
    calloutText: Color(0xFF1A0524),
    award: Color(0xFFB07BFF),
    rating: Color(0xFFB07BFF),
    focus: Color(0xFFD9B8FF),
    radius: 7,
    radiusSm: 5,
    radiusBtn: 7,
    radiusImg: 6,
    displayWeight: FontWeight.w700,
    displayTracking: -0.8,
    displaySize: 26,
    btnFill: Color(0xFF8B5CF6),
    btnText: Color(0xFFFFFFFF),
    btnGradient: LinearGradient(colors: [Color(0xFF8B5CF6), Color(0xFFD946A6)]),
    ghostFill: Color(0x12FFFFFF),
    ghostBorder: Color(0x47C496FF),
    ghostText: Color(0xFFF4EDFF),
    paneWash: RadialGradient(
      center: Alignment.topLeft,
      radius: 1.4,
      colors: [Color(0x298B5CF6), Color(0x008B5CF6)],
    ),
    idWash: RadialGradient(
      center: Alignment(-0.8, -0.6),
      radius: 1.2,
      colors: [Color(0x29D946A6), Color(0x00D946A6)],
    ),
  );

  // ── XIV · DEEP FIELD ────────────────────────────────────────────────────
  static const deepField = DetailTheme(
    id: 'deep_field',
    label: 'Deep Field',
    subtitle: 'Navy and ice blue, pill buttons on soft elevation',
    ground: Color(0xFF05132E),
    pane: Color(0xFF08183A),
    railBg: Color(0xFF040F26),
    panel: Color(0x12FFFFFF),
    hair: Color(0x2E96C8FF),
    tx: Color(0xFFEAF3FF),
    tx2: Color(0xADEAF3FF),
    tx3: Color(0x6BEAF3FF),
    accent: Color(0xFF5AC8FA),
    state: Color(0xFF5AC8FA),
    callout: Color(0xFF5AC8FA),
    calloutText: Color(0xFF04122B),
    award: Color(0xFF5AC8FA),
    rating: Color(0xFF5AC8FA),
    focus: Color(0xFF9BDCFF),
    radius: 12,
    radiusSm: 9,
    radiusImg: 9,
    displayWeight: FontWeight.w700,
    displayTracking: -0.6,
    displaySize: 25,
    btnFill: Color(0xFF5AC8FA),
    btnText: Color(0xFF04122B),
    btnWeight: FontWeight.w700,
    ghostFill: Color(0x1AFFFFFF),
    ghostBorder: Color(0x29FFFFFF),
    ghostText: Color(0xFFEAF3FF),
    paneWash: LinearGradient(
      begin: Alignment.topCenter,
      end: Alignment.bottomCenter,
      colors: [Color(0x175AC8FA), Color(0x005AC8FA)],
    ),
    shadow: [
      BoxShadow(
        color: Color(0xCC000000),
        blurRadius: 30,
        offset: Offset(0, 10),
      ),
    ],
  );

  // ── XV · GRAPHITE ───────────────────────────────────────────────────────
  static const graphite = DetailTheme(
    id: 'graphite',
    label: 'Graphite',
    subtitle: 'Cool slate and teal, denser rows — a tool, not a showcase',
    ground: Color(0xFF15181C),
    pane: Color(0xFF1A1E24),
    railBg: Color(0xFF101317),
    panel: Color(0x0DFFFFFF),
    hair: Color(0x1AFFFFFF),
    tx: Color(0xFFE8EDF2),
    tx2: Color(0xA1E8EDF2),
    tx3: Color(0x61E8EDF2),
    accent: Color(0xFF2DD4BF),
    state: Color(0xFF2DD4BF),
    callout: Color(0xFF2DD4BF),
    calloutText: Color(0xFF08201D),
    award: Color(0xFF2DD4BF),
    rating: Color(0xFF2DD4BF),
    focus: Color(0xFF5EEAD4),
    radius: 5,
    radiusSm: 4,
    radiusBtn: 5,
    radiusImg: 4,
    radiusCast: 4,
    displayWeight: FontWeight.w700,
    displayTracking: -0.5,
    slabTracking: 1.6,
    btnFill: Color(0xFF2DD4BF),
    btnText: Color(0xFF08201D),
    btnWeight: FontWeight.w700,
    ghostFill: Color(0x0FFFFFFF),
    ghostBorder: Color(0x24FFFFFF),
    ghostText: Color(0xFFE8EDF2),
    focusWidth: 2,
  );

  // ── XVI · VAULT ─────────────────────────────────────────────────────────
  static const vault = DetailTheme(
    id: 'vault',
    label: 'Vault',
    subtitle: 'A large light serif and almost no chrome — arthouse',
    ground: Color(0xFF0C0C0C),
    pane: Color(0xFF0C0C0C),
    railBg: Color(0xFF080808),
    panel: Color(0x0AFFFFFF),
    hair: Color(0x21FFFFFF),
    tx: Color(0xFFF7F5F0),
    tx2: Color(0x94F7F5F0),
    tx3: Color(0x57F7F5F0),
    accent: Color(0xFFF7F5F0),
    state: Color(0xFFE8C87A),
    callout: Color(0xFFE8C87A),
    calloutText: Color(0xFF1A1400),
    award: Color(0xFFE8C87A),
    rating: Color(0xFFF7F5F0),
    focus: Color(0xFFF7F5F0),
    radius: 0,
    radiusSm: 0,
    radiusBtn: 0,
    radiusImg: 0,
    displayFont: DetailFontRole.serif,
    displayWeight: FontWeight.w400,
    displayTracking: -0.3,
    displaySize: 31,
    slabSize: 9,
    slabTracking: 3.4,
    slabWeight: FontWeight.w500,
    btnFill: Color(0x00000000),
    btnText: Color(0xFFF7F5F0),
    btnWeight: FontWeight.w500,
    btnBorder: Color(0xFFF7F5F0),
    ghostFill: Color(0x00000000),
    ghostBorder: Color(0x47FFFFFF),
    ghostText: Color(0xFFF7F5F0),
    // Asks for 1px; the TV floor lifts it to 2.5 so the cursor survives.
    focusWidth: 1,
  );

  // ── XVII · SPECTRUM ─────────────────────────────────────────────────────
  static const spectrum = DetailTheme(
    id: 'spectrum',
    label: 'Spectrum',
    subtitle: 'Neutral chrome, one duotone gradient — colour as an event',
    ground: Color(0xFF0F0F12),
    pane: Color(0xFF141418),
    railBg: Color(0xFF0B0B0E),
    panel: Color(0x0DFFFFFF),
    hair: Color(0x1AFFFFFF),
    tx: Color(0xFFF2F2F5),
    tx2: Color(0xA3F2F2F5),
    tx3: Color(0x61F2F2F5),
    accent: Color(0xFF22D3EE),
    state: Color(0xFFE879F9),
    // The mock promises a duotone; only the PROGRESS BAR carries it, so a tick
    // or a percentage never becomes an unreadable gradient on small type.
    stateGradient: LinearGradient(
      colors: [Color(0xFF22D3EE), Color(0xFFE879F9)],
    ),
    callout: Color(0xFFE879F9),
    calloutText: Color(0xFF2A0524),
    award: Color(0xFF22D3EE),
    rating: Color(0xFF22D3EE),
    focus: Color(0xFF67E8F9),
    radius: 9,
    radiusSm: 7,
    radiusImg: 7,
    displayWeight: FontWeight.w800,
    displayTracking: -0.8,
    displaySize: 25,
    btnFill: Color(0xFF22D3EE),
    btnText: Color(0xFF06202A),
    btnGradient: LinearGradient(colors: [Color(0xFF22D3EE), Color(0xFFE879F9)]),
    ghostFill: Color(0x0FFFFFFF),
    ghostBorder: Color(0x26FFFFFF),
    ghostText: Color(0xFFF2F2F5),
  );

  // ── XVIII · VERDANT ─────────────────────────────────────────────────────
  static const verdant = DetailTheme(
    id: 'verdant',
    label: 'Verdant',
    subtitle: 'Near-black and a hot lime — reads fastest across a room',
    ground: Color(0xFF0A0F0A),
    pane: Color(0xFF0D140D),
    railBg: Color(0xFF070B07),
    panel: Color(0x12A3E635),
    hair: Color(0x2EA3E635),
    tx: Color(0xFFF0F5EC),
    tx2: Color(0xA3F0F5EC),
    tx3: Color(0x61F0F5EC),
    accent: Color(0xFFA3E635),
    state: Color(0xFFA3E635),
    callout: Color(0xFFA3E635),
    calloutText: Color(0xFF0A1400),
    award: Color(0xFFA3E635),
    rating: Color(0xFFA3E635),
    focus: Color(0xFFBEF264),
    radius: 6,
    radiusSm: 5,
    radiusImg: 5,
    displayWeight: FontWeight.w800,
    displayUpper: true,
    displayTracking: -0.4,
    displaySize: 24,
    slabTracking: 1.8,
    btnFill: Color(0xFFA3E635),
    btnText: Color(0xFF0A1400),
    btnWeight: FontWeight.w800,
    ghostFill: Color(0x0FFFFFFF),
    ghostBorder: Color(0x47A3E635),
    ghostText: Color(0xFFF0F5EC),
    focusWidth: 3,
  );

  // ── XIX · FROST ─────────────────────────────────────────────────────────
  static const frost = DetailTheme(
    id: 'frost',
    label: 'Frost',
    subtitle: 'Translucent surfaces catching light from different angles',
    ground: Color(0xFF1C2230),
    pane: Color(0xFF232A3A),
    railBg: Color(0xFF1E2432),
    panel: Color(0x1FFFFFFF),
    hair: Color(0x33FFFFFF),
    tx: Color(0xFFFFFFFF),
    tx2: Color(0xB8FFFFFF),
    tx3: Color(0x7AFFFFFF),
    accent: Color(0xFFFFFFFF),
    state: Color(0xFFA7F3D0),
    callout: Color(0xFFA7F3D0),
    calloutText: Color(0xFF04241B),
    award: Color(0xFFFFFFFF),
    rating: Color(0xFFFFFFFF),
    focus: Color(0xFFFFFFFF),
    radius: 16,
    radiusSm: 12,
    radiusImg: 12,
    displayWeight: FontWeight.w700,
    displayTracking: -0.65,
    displaySize: 26,
    btnFill: Color(0xEBFFFFFF),
    btnText: Color(0xFF141A26),
    ghostFill: Color(0x29FFFFFF),
    ghostBorder: Color(0x42FFFFFF),
    ghostText: Color(0xFFFFFFFF),
    paneWash: LinearGradient(
      begin: Alignment.topLeft,
      end: Alignment.bottomRight,
      colors: [Color(0x1AFFFFFF), Color(0x05FFFFFF)],
    ),
    railWash: LinearGradient(
      begin: Alignment.bottomLeft,
      end: Alignment.topRight,
      colors: [Color(0x14FFFFFF), Color(0x03FFFFFF)],
    ),
    idWash: LinearGradient(
      begin: Alignment.topLeft,
      end: Alignment.bottomRight,
      colors: [Color(0x1AFFFFFF), Color(0x05FFFFFF)],
    ),
    shadow: [
      BoxShadow(
        color: Color(0xBF000000),
        blurRadius: 44,
        offset: Offset(0, 14),
      ),
    ],
  );

  // ── XX · CINEMASCOPE ────────────────────────────────────────────────────
  static const cinemascope = DetailTheme(
    id: 'cinemascope',
    label: 'Cinemascope',
    subtitle: "Wide thin caps and gold hairlines — a film's own title card",
    ground: Color(0xFF070707),
    pane: Color(0xFF0A0A0A),
    railBg: Color(0xFF050505),
    panel: Color(0x0DF0E1C8),
    hair: Color(0x2EF0E1C8),
    tx: Color(0xFFF2E7D5),
    tx2: Color(0x99F2E7D5),
    tx3: Color(0x5CF2E7D5),
    accent: Color(0xFFE8C07A),
    state: Color(0xFFE8C07A),
    callout: Color(0xFFE8C07A),
    calloutText: Color(0xFF1A1204),
    award: Color(0xFFE8C07A),
    rating: Color(0xFFE8C07A),
    focus: Color(0xFFF2E7D5),
    radius: 2,
    radiusSm: 2,
    radiusBtn: 2,
    radiusImg: 2,
    radiusCast: 0,
    displayWeight: FontWeight.w300,
    displayUpper: true,
    displayTracking: 3.8,
    displaySize: 21,
    slabTracking: 3.2,
    slabWeight: FontWeight.w500,
    btnFill: Color(0x00000000),
    btnText: Color(0xFFE8C07A),
    btnWeight: FontWeight.w500,
    btnBorder: Color(0xFFE8C07A),
    ghostFill: Color(0x00000000),
    ghostBorder: Color(0x4DF0E1C8),
    ghostText: Color(0xFFF2E7D5),
    // Asks for 1px; the TV floor lifts it to 2.5.
    focusWidth: 1,
    grain: 0.05,
  );

  /// Registry, in picker order: the concept set, then the premium set.
  static const List<DetailTheme> all = [
    signal,
    noir,
    broadsheet,
    phosphor,
    aurora,
    concrete,
    velvet,
    blueprint,
    broadcast,
    sepia,
    obsidian,
    halo,
    prestige,
    deepField,
    graphite,
    vault,
    spectrum,
    verdant,
    frost,
    cinemascope,
  ];

  /// The five premium looks, as detail cores.
  ///
  /// Separate from [all] rather than appended to it: [all] is `const` and
  /// pinned at twenty by `detail_theme_test.dart`, and these are DERIVED —
  /// `ThemeSpec.toCore()` runs colour math, so they cannot be const and must
  /// not be recomputed per lookup. `static final` gives one lazy build each
  /// for the process.
  ///
  /// The cull merges the two lists by deleting the first one.
  static final List<DetailTheme> premium = [
    for (final s in PremiumLooks.all) s.toCore(),
  ];

  /// Every look this build can resolve, premium first — picker order.
  static List<DetailTheme> get catalogue => [...premium, ...all];

  static DetailTheme byId(String id) {
    for (final t in premium) {
      if (t.id == id) return t;
    }
    for (final t in all) {
      if (t.id == id) return t;
    }
    return signal;
  }
}
